import 'package:flutter/material.dart';

const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Colors.blue,
  onPrimary: Color(0xFF000000),
  primaryContainer: Color(0xFFFFDAD6),
  onPrimaryContainer: Color(0xFF410003),
  secondary: Color(0xFF775653),
  onSecondary: Color(0xFFEBEBF1),
  secondaryContainer: Color(0xFFFFDAD6),
  onSecondaryContainer: Color(0xFF2C1513),
  tertiary: Color(0xFF725B2E),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFFEDEA6),
  onTertiaryContainer: Color(0xFF261900),
  error: Color(0xFFBA1A1A),
  errorContainer: Color(0xFFFFDAD6),
  onError: Color(0xFFFFFFFF),
  onErrorContainer: Color(0xFF410002),
  background: Color(0xFFFFFBFF),
  onBackground: Color(0xFFEBEBF1),
  surface: Color(0xFFFFFBFF),
  onSurface: Color(0xFF201A19),
  surfaceVariant: Color(0xFFF5DDDB),
  onSurfaceVariant: Color(0xFF534341),
  outline: Color(0xFF857371),
  onInverseSurface: Color(0xFFFBEEEC),
  inverseSurface: Color(0xFF362F2E),
  inversePrimary: Color(0xFFFFB4AC),
  shadow: Color(0xFF000000),
  //surfaceTint: Color(0xFFC00017),
);
