name: goo_rent
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  get: ^4.6.5
  # flutter_facebook_auth: ^5.0.11
  firebase_auth: ^4.6.2
  google_sign_in: ^6.1.3
  go_router: ^7.1.1
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  flutter_screenutil: ^5.6.0
  toggle_switch: ^2.0.1
  provider: ^6.0.4
  pin_code_fields: ^7.4.0
  dropdown_button2: ^1.0.1
  another_xlider: ^1.1.2
  calendar_date_picker2: ^0.4.5
  country_code_picker: ^3.0.0
  dotted_line: ^3.1.0
  share_plus: ^7.0.2
  get_storage: ^2.1.1
  http: ^0.13.6
  intl: ^0.18.0
  carousel_slider: ^4.2.1
  animated_custom_dropdown: ^1.5.0
  syncfusion_flutter_sliders: ^21.2.8
  syncfusion_flutter_core: ^21.2.8
  global_configs: ^1.1.2
  json_annotation: ^4.6.0
  json_serializable: ^6.1.3
  flutter_local_notifications: ^15.0.0
  firebase_messaging: ^14.6.4
  device_info_plus: ^9.0.2
  flutter_app_badger: ^1.5.0
  flutter_hooks: ^0.19.0
  google_maps_flutter: ^2.2.6
  geolocator: ^9.0.2
  flutter_polyline_points: ^1.0.0
  flutter_native_splash: ^2.2.5
  geocoding: ^2.1.0
  shimmer: ^3.0.0
  readmore: ^2.2.0
  dynamic_height_grid_view: ^0.0.3
  smart_grid_view_nls: ^0.2.2
  
  
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^2.13.1
  flutter_svg_provider: ^1.0.3
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  # json_serializable: ^6.1.3
  

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
     - assets/image/
     - assets/images/
     - assets/icons/
     - assets/flags/
     - assets/image2/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Kantumruy
      fonts:
        - asset: assets/fonts/KantumruyPro-Regular.ttf
        - asset: assets/fonts/KantumruyPro-Thin.ttf
        - asset: assets/fonts/KantumruyPro-Light.ttf
        - asset: assets/fonts/KantumruyPro-Medium.ttf
          weight: 700
        - asset: assets/fonts/KantumruyPro-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/KantumruyPro-Bold.ttf
          weight: 800

  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
