// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5LIEI7IzlAIwZnRiR2EA4d1pjir-bNdw',
    appId: '1:340131520441:web:22dc2d946e98eb721d6068',
    messagingSenderId: '340131520441',
    projectId: 'goorent',
    authDomain: 'goorent.firebaseapp.com',
    storageBucket: 'goorent.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHpGHxBw3NC33E7eVB0zt9FKTiNmF62ts',
    appId: '1:340131520441:android:92996672b2d8631f1d6068',
    messagingSenderId: '340131520441',
    projectId: 'goorent',
    storageBucket: 'goorent.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqg1OVhwMIhOqTvqC2J_-fiXaSNfUcUgE',
    appId: '1:340131520441:ios:618030b6f5f89a571d6068',
    messagingSenderId: '340131520441',
    projectId: 'goorent',
    storageBucket: 'goorent.appspot.com',
    androidClientId: '340131520441-qjeddhrlo9138nj5enqb2mfrifg86cs9.apps.googleusercontent.com',
    iosClientId: '340131520441-7v9u8jmi9us8cdqta0s5qtgfkt6h6g8p.apps.googleusercontent.com',
    iosBundleId: 'com.example.gooRent',
  );
}
